# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:7.5

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mongo

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

variables:
  MONGO_URL: 'mongodb://mongo/app_name'

test_backend:
  script:
   - npm install --silent
   - cross-env LOG_LEVEL=error NODE_ENV=test PORT=8080 node node_modules/.bin/ava --serial -v

test_lint:
  script:
   - npm install --silent
   - npm run lint
